disabled_rules:
  - trailing_whitespace
  - line_length
  - unused_optional_binding
  - function_body_length
opt_in_rules:
  - empty_count
  - no_grouping_extension
excluded:
  - Carthage
identifier_name:
  excluded:
    - id
    - to
    - on